In [2]:
import os
import pickle
import tensorflow as tf
import numpy as np
import pandas as pd
import sklearn as sk
from sklearn.metrics import roc_curve, auc
from timeit import default_timer as timer

import pickle
from sklearn.preprocessing import LabelBinarizer

# needed for plotting
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
current_palette = sns.color_palette()
import pdb
from numpy import array
import random as rd
import sys
#reload(sys)
#sys.setdefaultencoding()

In [3]:
# Requires TensorFlow V.12

tf.__version__

'1.2.0'

In [4]:
def getkey(item):
    fpr, tpr, _ = roc_curve(test_labels.ravel(), test_preds[item])
    roc_auc = auc(fpr, tpr)
    return roc_auc

def plotROC(testlabels, test_preds):
    classifiers = list(test_preds.keys())

    # Plot all ROC curves
    plt.figure(figsize=(15,9))
    for i, clf in zip(range(len(classifiers)), sorted(classifiers, key=getkey, reverse=True)):
        fpr, tpr, _ = roc_curve(testlabels.ravel(), test_preds[clf] )
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr,
                 label='ROC curve '+ clf +  ' (area = {0:0.4f})'
                       ''.format(roc_auc), linestyle='-', linewidth=2)


    plt.plot([0, 1], [0, 1], 'k--', lw=2)
    plt.xlim([-0.1, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Comparison of multiclass ROC curves')
    plt.legend(loc="lower right", fontsize=14)
    plt.show()

In [5]:
data = pickle.load(open('features_file.p', 'rb'))
data.tail()

#print (data[2000:4000])

shape  label  music  noise  silence  speech  \
3004  (1, 193)  noise    0.0    1.0      0.0     0.0   
3005  (1, 193)  noise    0.0    1.0      0.0     0.0   
3006  (1, 193)  noise    0.0    1.0      0.0     0.0   
3007  (1, 193)  noise    0.0    1.0      0.0     0.0   
3008  (1, 193)  noise    0.0    1.0      0.0     0.0   

                                                 sample  
3004  [-223.41727359645648, 99.13116797039905, -57.5...  
3005  [-213.539618903399, 100.16073068189185, -50.19...  
3006  [-219.8521240138423, 96.86084396902716, -60.07...  
3007  [-226.19836233959882, 88.05429771807319, -69.2...  
3008  [-351.9375465095595, 108.25304673045771, -40.4...

In [6]:
#pdb.set_trace()
print(data.columns)

print(data.shape)

Index(['shape', 'label', 'music', 'noise', 'silence', 'speech', 'sample'], dtype='object')
(3009, 7)


In [7]:
s = list(data['sample'])
s = pd.DataFrame(s)
data_cols = s.columns
s['label'] = data['label']
print('working dataframe\'s shape:', s.shape)
#pdb.set_trace()
print(s['label'])

working dataframe's shape: (3009, 194)
0       music
1       music
2       music
3       music
4       music
5       music
6       music
7       music
8       music
9       music
10      music
11      music
12      music
13      music
14      music
15      music
16      music
17      music
18      music
19      music
20      music
21      music
22      music
23      music
24      music
25      music
26      music
27      music
28      music
29      music
        ...  
2979    noise
2980    noise
2981    noise
2982    noise
2983    noise
2984    noise
2985    noise
2986    noise
2987    noise
2988    noise
2989    noise
2990    noise
2991    noise
2992    noise
2993    noise
2994    noise
2995    noise
2996    noise
2997    noise
2998    noise
2999    noise
3000    noise
3001    noise
3002    noise
3003    noise
3004    noise
3005    noise
3006    noise
3007    noise
3008    noise
Name: label, Length: 3009, dtype: object


In [8]:
test_preds = {}
#train=s[0:3500]
#test=s[3500:7035]
train =s.sample(frac=0.7)#data division 70% randomly picked samples for training
test = s.loc[~s.index.isin(train.index)]#remaining 30% randomly picked samples
LB = LabelBinarizer().fit(train['label'])
test_labels = LB.transform(test['label'])
scaler1 = sk.preprocessing.StandardScaler().fit(train.loc[:,data_cols])
train.loc[:,data_cols] = scaler1.transform(train.loc[:,data_cols])
test.loc[:,data_cols] = scaler1.transform(test.loc[:,data_cols])
#print(test.loc)
#print(LB)
print(test_labels[200:400])
# truncate data
#data_cols = data_cols[:1000]
#pdb.set_trace()
# print shapes
#print('train shape {}\ntest  shape {}\ncommon factors: 1, 2, 3, 6, 9, 18, 97, 194, 291, 582, 873, 1746'.format(train.shape, test.shape))

C:\Users\kkhalid\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]

In [ ]:
#print(test)

In [ ]:
#pdb.set_trace()

del data, s

In [9]:
def accuracy(predictions, labels):
    return (100.0 * np.sum(np.argmax(predictions, 1) == np.argmax(labels, 1))
            / predictions.shape[0])

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.01)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def test_accuracy(session, test_data=test, during = True):
    test_data.reset_index(inplace=True, drop=True)
    epoch_pred = session.run(test_prediction, feed_dict={tf_data : test_data.loc[0:check_size-1,data_cols], keep_prob : 1.0})
    for i in range(check_size, test_data.shape[0], check_size):
        epoch_pred = np.concatenate([epoch_pred, session.run(test_prediction, 
                                    feed_dict={tf_data : test_data.loc[i:i+check_size-1,data_cols], keep_prob : 1.0})], axis=0)
    if during:
        return accuracy(epoch_pred, test_labels)
    else:
        return epoch_pred

In [10]:
num_labels = 4
batch_size = 97
acc_over_time = {}
def Run_Session(num_epochs, name, k_prob=1.0, mute=False, record=False):
    global train
    

    
    
    
    start = timer()
    with tf.Session(graph=graph) as session:
        if record:
            merged = tf.merge_all_summaries()  
            writer = tf.train.SummaryWriter("/tmp/tensorflowlogs", session.graph)
        #tf.initialize_all_variables().run()
        tf.global_variables_initializer().run()

        print("Initialized")
        
        saver=tf.train.Saver()
        save_dir='C:/Users/kkhalid/project_kk'
        save_path = os.path.join(save_dir, 'CNN_model_trained')
        #pdb.set_trace()
        
        accu = []
        
        for epoch in range(num_epochs):
            
            # get batch
            train_batch = train.sample(batch_size)
            
            t_d = train_batch[data_cols]
            t_l = LB.transform(train_batch['label'])
            
            # make feed dict
            feed_dict = { tf_data : t_d, train_labels : t_l, keep_prob : k_prob}
            
            
           
            #pdb.set_trace()
            # run model on batch
            _, l, predictions = session.run([optimizer, loss, prediction], feed_dict=feed_dict)
            
            #saver.save(sess=session, save_path=save_path)



            #print(predictions)
            #print(loss)
            #pdb.set_trace()
            # mid model accuracy checks 
            if (epoch % 1000 == 0) and not mute:
                print("\tMinibatch loss at epoch {}: {}".format(epoch, l))
                print("\tMinibatch accuracy: {:.1f}".format(accuracy(predictions, t_l)))
            if (epoch % 1000 == 0) and not mute:
                print("Test accuracy: {:.1f}".format(test_accuracy(session, during=True)))
            if (epoch % 1000 == 0) and not mute:
                accu.append(tuple([epoch, test_accuracy(session, during=True)]))
                
                
                
                
        #saver=tf.train.Saver()
        saver.save(sess=session, save_path=save_path)
     
        
        #saver.restore(session,tf.train.latest_checkpoint("C:/Users/kkhalid/project_kk/model-ckpt/checkpoint"))
        
        #print(session.run('w1:0'))
        # record accuracy and predictions
        
        test_preds[name] = test_accuracy(session, during=False)
        print("Final Test accuracy: {:.1f}".format(accuracy(test_preds[name], test_labels)))
        end = timer()
        test_preds[name] = test_preds[name].ravel()
        acc_over_time[name] = accu
        print("time taken: {0} minutes {1:.1f} seconds".format((end - start)//60, (end - start)%60))
        #tf.train.export_meta_graph()
        #saver=tf.train.import_meta_graph('C:/Users/kkhalid/project_kk/model-ckpt/trained_py_variation_6k.ckpt.meta')
        
        #saver.restore(session,tf.train.latest_checkpoint("C:/Users/kkhalid/project_kk/model-ckpt/checkpoint"))
        #saver.restore(sess=session, save_path=save_path)


In [11]:
# constants
num_labels = 4

batch_size = 97
check_size = 582
feature_size = 193

n_hidden1 = 800
n_hidden2 = 1000
n_hidden3 = 1000
n_hidden4 = 800

beta = 0.01

graph = tf.Graph()
with graph.as_default():
    # placeholders
    tf_data = tf.placeholder(tf.float32, shape=[None, feature_size],name='input_data')
    train_labels = tf.placeholder(tf.float32, shape=[None,num_labels],name='input_labels')
    keep_prob = tf.placeholder(tf.float32)
    #pdb.set_trace()
    # weights and biases
    layer1_weights = weight_variable([feature_size, n_hidden1])
    layer1_biases = bias_variable([n_hidden1])
    layer2_weights = weight_variable([n_hidden1, n_hidden2])
    layer2_biases = bias_variable([n_hidden2])
    layer3_weights = weight_variable([n_hidden2, n_hidden3])
    layer3_biases = bias_variable([n_hidden3])
    layer4_weights = weight_variable([n_hidden3, n_hidden4])
    layer4_biases = bias_variable([n_hidden4])
    layer5_weights = weight_variable([n_hidden4, num_labels])
    layer5_biases = bias_variable([num_labels])

     # model
    def model(data, proba=0.8):
        layer1 = tf.nn.relu(tf.matmul(data, layer1_weights) + layer1_biases)
        layer1 = tf.nn.dropout(layer1, proba)
        
        layer2 = tf.nn.relu(tf.matmul(layer1, layer2_weights) + layer2_biases)
        layer2 = tf.nn.dropout(layer2, proba)
        
        layer3 = tf.nn.relu(tf.matmul(layer2, layer3_weights) + layer3_biases)
        layer3 = tf.nn.dropout(layer3, proba)
        
        layer4= tf.nn.relu(tf.matmul(layer3, layer4_weights) + layer4_biases)
        layer4 = tf.nn.dropout(layer4, proba)
        
        return tf.matmul(layer4, layer5_weights) + layer5_biases

    # Training computation.
    logits = model(tf_data, keep_prob)
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=train_labels) +
                         beta*tf.nn.l2_loss(layer1_weights) +
                         beta*tf.nn.l2_loss(layer1_biases) +
                         beta*tf.nn.l2_loss(layer2_weights) +
                         beta*tf.nn.l2_loss(layer2_biases) +
                         beta*tf.nn.l2_loss(layer3_weights) +
                         beta*tf.nn.l2_loss(layer3_biases) +
                         beta*tf.nn.l2_loss(layer4_weights) +
                         beta*tf.nn.l2_loss(layer4_biases) +
                         beta*tf.nn.l2_loss(layer5_weights) +
                         beta*tf.nn.l2_loss(layer5_biases))

    # Optimizer.
    optimizer = tf.train.AdamOptimizer(1e-4).minimize(loss)
   


    prediction = tf.nn.softmax(logits,name='op_to_restore')
    test_prediction = tf.nn.softmax(model(tf_data, proba=0.7),name='op_to_restore')  
    print('Basic DeepNN model made')

Basic DeepNN model made


In [14]:
Run_Session(12000, 'DeepNN',0.8)

#pdb.set_trace()

Initialized
	Minibatch loss at epoch 0: 2.6360561847686768
	Minibatch accuracy: 21.6
Test accuracy: 24.0
	Minibatch loss at epoch 1000: 0.5142006874084473
	Minibatch accuracy: 89.7
Test accuracy: 87.7
	Minibatch loss at epoch 2000: 0.3138744831085205
	Minibatch accuracy: 97.9
Test accuracy: 89.0
	Minibatch loss at epoch 3000: 0.378925085067749
	Minibatch accuracy: 94.8
Test accuracy: 88.8
	Minibatch loss at epoch 4000: 0.3511411249637604
	Minibatch accuracy: 96.9
Test accuracy: 88.5
	Minibatch loss at epoch 5000: 0.28055280447006226
	Minibatch accuracy: 96.9
Test accuracy: 88.9
	Minibatch loss at epoch 6000: 0.3175709843635559
	Minibatch accuracy: 97.9
Test accuracy: 88.5
	Minibatch loss at epoch 7000: 0.2723849415779114
	Minibatch accuracy: 97.9
Test accuracy: 89.6
	Minibatch loss at epoch 8000: 0.3053362965583801
	Minibatch accuracy: 95.9
Test accuracy: 88.2
	Minibatch loss at epoch 9000: 0.2746383547782898
	Minibatch accuracy: 99.0
Test accuracy: 88.6
	Minibatch loss at epoch 10000:

In [12]:
# single layer CNN
num_labels = 4

batch_size = 97
check_size = 582
feature_size = 193
patch_size = 10
num_channels = 1
depth1 = 64

num_hidden = 1050

beta = 0.001

graph = tf.Graph()
with graph.as_default():
    
    tf_data = tf.placeholder(tf.float32, shape=(None, feature_size),name='input_data')
    train_labels = tf.placeholder(tf.float32, shape=(None, num_labels))
    keep_prob = tf.placeholder(tf.float32)
    
    # Variables.
    layer1_weights = weight_variable([1, patch_size, 1, depth1])
    layer1_biases = bias_variable([depth1])
    layer2_weights = weight_variable([(feature_size//2 + 1)* depth1, num_hidden])
    layer2_biases = bias_variable([num_hidden])
    layer3_weights = weight_variable([num_hidden, num_labels])
    layer3_biases = bias_variable([num_labels])

    
    # Model with dropout
    def model(data, distort=None, proba=keep_prob):
        
        #if distort is not None:
        #    data = tf.image.random_brightness(data, 0.9, seed=58)
        #    data = tf.image.random_contrast(data, 0.1, 1.9, seed=58)
        
        # Convolution
        conv1 = tf.nn.conv2d(data, layer1_weights, [1, 1, 2, 1] , padding='SAME') + layer1_biases
        pooled1 = tf.nn.max_pool(tf.nn.relu(conv1), ksize=[1, 1, 2, 1],strides=[1, 1, 1, 1], padding='SAME')

        # Fully Connected Layer
        shape = pooled1.get_shape().as_list()
        reshape = tf.reshape(pooled1, [-1, shape[1] * shape[2] * shape[3]])
        full2 = tf.nn.relu(tf.matmul(reshape, layer2_weights) + layer2_biases)
        
        # Dropout
        full2 = tf.nn.dropout(full2, proba)
        
        return tf.matmul(full2, layer3_weights) + layer3_biases

    # Training computation.
    logits = model(tf.expand_dims(tf.expand_dims(tf_data, [-1]), 1), distort=True, proba=keep_prob)
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=train_labels) +
                         beta*tf.nn.l2_loss(layer1_weights) +
                         beta*tf.nn.l2_loss(layer1_biases) +
                         beta*tf.nn.l2_loss(layer2_weights) +
                         beta*tf.nn.l2_loss(layer2_biases) +
                         beta*tf.nn.l2_loss(layer3_weights) +
                         beta*tf.nn.l2_loss(layer3_biases))

    # Optimizer.
    optimizer = tf.train.AdamOptimizer(1e-4).minimize(loss)

    # Predictions for the training, validation, and test data.
    prediction = tf.nn.softmax(logits)
    test_prediction = tf.nn.softmax(model(tf.expand_dims(tf.expand_dims(tf_data, [-1]), 1), proba=1.0),name='op_to_restore')  
    print('Basic CNN model made')


Basic CNN model made


In [15]:
Run_Session(10000, 'CNN', .8)

Initialized
	Minibatch loss at epoch 0: 1.6506565809249878
	Minibatch accuracy: 20.6
Test accuracy: 26.4
	Minibatch loss at epoch 1000: 0.26065221428871155
	Minibatch accuracy: 93.8
Test accuracy: 88.7
	Minibatch loss at epoch 2000: 0.20331141352653503
	Minibatch accuracy: 94.8
Test accuracy: 89.5
	Minibatch loss at epoch 3000: 0.13751330971717834
	Minibatch accuracy: 97.9
Test accuracy: 88.5
	Minibatch loss at epoch 4000: 0.15481409430503845
	Minibatch accuracy: 94.8
Test accuracy: 89.3
	Minibatch loss at epoch 5000: 0.12044704705476761
	Minibatch accuracy: 96.9
Test accuracy: 90.0
	Minibatch loss at epoch 6000: 0.1327853947877884
	Minibatch accuracy: 96.9
Test accuracy: 89.7
	Minibatch loss at epoch 7000: 0.13085632026195526
	Minibatch accuracy: 96.9
Test accuracy: 89.8
	Minibatch loss at epoch 8000: 0.09798742830753326
	Minibatch accuracy: 97.9
Test accuracy: 90.0
	Minibatch loss at epoch 9000: 0.12513801455497742
	Minibatch accuracy: 96.9
Test accuracy: 90.3
Final Test accuracy: 88

In [ ]:
fig = plt.figure(figsize=[12,7])
plt.title('Accuracy for 193Feature set by epoch', fontsize=20)
plt.plot(np.array(acc_over_time['DeepNN'])[:,0], np.array(acc_over_time['DeepNN'])[:,1], label='DeepNN')
plt.plot(np.array(acc_over_time['CNN'])[:,0], np.array(acc_over_time['CNN'])[:,1], label='CNN')
plt.xlabel('Epoch', fontsize=18)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.ylabel('Accuracy (%)', fontsize=18)
plt.ylim([0, 100])
plt.xlim([0, 10000])
plt.legend(loc="lower right", fontsize=18)
plt.show()

In [ ]:
plotROC(test_labels, test_preds)

In [ ]:
# numeralize labels
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
test_batch = le.fit_transform(test['label'])


def confusion(true, predicted):
    matrix = np.zeros([4,4])
    pred = predicted.reshape((predicted.shape[0]//4, 4))

    count = 0
    for lab in test_batch:
        matrix[lab] += pred[count].round()
        count += 1
        
    return matrix

In [ ]:
print(tf_data)

In [ ]:
matrix = confusion(test_batch, test_preds['DeepNN'])

plt.figure(figsize=[10,10])
plt.imshow(matrix, cmap='hot', interpolation='nearest',  vmin=0, vmax=100)
plt.colorbar()
plt.title('DeepNN Confusion Map', fontsize=18)
plt.ylabel('Actual', fontsize=18)
plt.xlabel('Predicted', fontsize=18)
plt.grid(b=False)
plt.yticks(range(4), le.classes_, fontsize=14)
plt.xticks(range(4), le.classes_, fontsize=14, rotation='vertical')
plt.show()

In [ ]:
matrix = confusion(test_batch, test_preds['CNN'])

fig = plt.figure(figsize=[10,10])
plt.imshow(matrix, cmap='hot', interpolation='none', vmin=0, vmax=100)
plt.colorbar()
plt.title('CNN Confusion Map', fontsize=18)
plt.ylabel('Actual', fontsize=18)
plt.xlabel('Predicted', fontsize=18)
plt.grid(b=False)
plt.yticks(range(4), le.classes_, fontsize=14)
plt.xticks(range(4), le.classes_, fontsize=14, rotation='vertical')
plt.show()

In [ ]:

with tf.Session() as sess:    
    saver = tf.train.import_meta_graph('C:/Users/kkhalid/project_kk/model-ckpt/trained_py_variation_6k.ckpt.meta')
    saver.restore(sess,tf.train.latest_checkpoint('C:/Users/kkhalid/project_kk/model-ckpt/checkpoint.ckpt/checkpoint.ckpt',latest_filename=None))
    print(sess.run('w1:0'))
##Model has been restored. Above statement will print the saved value of w1.